main:
  # Assume in centimeters
  ground_height: 50
  window_height: 480
  window_width: 640

  bi_width: 50
  bi_height: 10
  bi_mass: 5
  gravity: 9.81
  max_thrust: 100 # Newtons, is that reasonable?

  